theme: jekyll-theme-minimal
title: Co-Designing Transit
description: CMU Human-Computer Interaction Institute project on the future of transit work and human-machine teaming with transit automation technologies
